version: '3.9'

services:
  frontend:
    image: ${REGISTRY}gpf-geocodeur
    build: .
    container_name: gpf-geocodeur
    environment:
      - NEXT_PUBLIC_API_URL=http://gpf-geocodeur-api
      - NEXT_PUBLIC_ROOT_URL=http://gpf-geocodeur
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - gpf-geocodeur

networks:
  gpf-geocodeur:
    name: gpf-geocodeur-network
